/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'requirement' : IDL.Text,
  'isProcessed' : IDL.Bool,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'deleteProcessed' : IDL.Func([], [], []),
  'deleteSubmission' : IDL.Func([IDL.Nat], [], []),
  'getSubmissionCount' : IDL.Func([IDL.Bool], [IDL.Nat], ['query']),
  'getSubmissions' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'markAllProcessed' : IDL.Func([], [], []),
  'markAsProcessed' : IDL.Func([IDL.Nat], [], []),
  'searchByEmail' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'requirement' : IDL.Text,
    'isProcessed' : IDL.Bool,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'deleteProcessed' : IDL.Func([], [], []),
    'deleteSubmission' : IDL.Func([IDL.Nat], [], []),
    'getSubmissionCount' : IDL.Func([IDL.Bool], [IDL.Nat], ['query']),
    'getSubmissions' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'markAllProcessed' : IDL.Func([], [], []),
    'markAsProcessed' : IDL.Func([IDL.Nat], [], []),
    'searchByEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };